import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Montserrat } from 'next/font/google';
import { Suspense } from "react";
import RouteLoader from "./loading";
import { CustomThemeProvider } from "@/context/ThemeContext";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const montserrat = Montserrat({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-montserrat',
});

// Metadata da página
export const metadata: Metadata = {
  title: "Pega Blinders",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="pt">
      <body className="h-full w-full bg-white" cz-shortcut-listen="false">
        <AppRouterCacheProvider>
          <CustomThemeProvider>
            <Suspense fallback={<RouteLoader />}>
            {children}
            </Suspense>
          </CustomThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}



